apiVersion: v1
kind: BuildConfig
metadata:
  name: snaik17.spring-igc-jenk
  labels:
    app: spring-igc-jenk
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/snaik17/spring-igc-jenk.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-smi2
        - name: BRANCH
          value: master
